### PR TITLE
Decaffeinate Mapscii

### PR DESCRIPTION
**Pull request by jaller94**
New Year's resolution: Less CoffeeScript, more standard ECMAScript

Merry Christmas!

### CODE REVIEW

**Comment by rastapasta** [comment]
Hey hey @jaller94, welcome on board and thanks for the early christmas present and efforts of decaffinating MapSCII :coffee::smile: :+1:  Hope you had an exciting ride understanding the code.

I would love to push your changes into fresh branch to give it another refactor iteration before hitting master, enhancing the ES6 even further towards async/await  + some other patters I fell in love with - and most likely a TypeScript adaption.

So much in the pipeline :smile_cat: 

Would you mind me doing this and taking over for the next step?

Thanks again for your contribution, bests and happy xmas :christmas_tree:

**Comment by jaller94** [comment]
Hi again,
sounds good. I merged it with my `master`, however, I would like to see efforts being consolidated to one codebase. (no fork intended)

* more ES6 and async/await - sounds awesome!
* TypeScript - I hope it does not mean the project gets locked into the next framework.

I would also like to see/introduce some tests, mainly to ensure the package-ish classes like src/BrailleBuffer.js get tested - maybe using Jest?

Sure, take over and thanks for this awesome and geeky OSM viewer.

**Comment by jaller94** [comment]
Another note: I added my repo to codeclimate to help me identify maintainability issues.
https://codeclimate.com/github/jaller94/mapscii

**Comment by jaller94** [comment]
@rastapasta Do you have a rough time estimate for the refactoring?
May I help with anything?

**Comment by jaller94** [comment]
Hey, @rastapasta. Are there any news regarding other clean up projects?

**Comment by jaller94** [comment]
It has been almost a year since this project has had its last commit on `staging`.
I would be willing to take over the maintenance.

**Comment by jaller94** [comment]
For the record: It felt **very satisfying** to click on this merge button myself after a year. 😜👌

**Pull request merged**
